Expense list updated: Expense list updated with state and map
BCH-REACT20S-Project-1-Group-2/BCH-REACT20S-Project-1-Group-2.github.io pull request #32
Opened 2020-11-06 06:48 UTC by khushboogoyal88

2020-11-06 06:49 UTC, khushboogoyal88 commented
I am however now confused, shud I have instead put the state in Expense page  or directly in App.js

2020-11-06 07:41 UTC, vesasuikkola requested changes

2020-11-06 07:41 UTC, vesasuikkola commented on frontend/src/components/ExpenseList.js
> +    expenses: [
Please rename to "categories"

2020-11-06 07:41 UTC, vesasuikkola commented on frontend/src/components/ExpenseList.js
> +    const expenseList = this.state.expenses.map((item) => {
Please rename to categoryList

2020-11-06 07:41 UTC, vesasuikkola commented
> I am however now confused, shud I have instead put the state in Expense page or directly in App.js

This is ok for now, we'll anyways need to move the list to localstorage/backend later. I'll raise a separate PBI for that.

2020-11-07 09:59 UTC, khushboogoyal88 commented
I have made the name convention changes as you requested. Please have a look.

2020-11-07 11:01 UTC, vesasuikkola approved these changes, later dismissed

2020-11-07 11:03 UTC, vesasuikkola commented on frontend/src/components/ExpenseList.js
> +    expenses: [
12c05b0ab8d6a0ff42c54ec8615cd663695e66a6 OK

2020-11-07 11:03 UTC, vesasuikkola commented on frontend/src/components/ExpenseList.js
> +    const expenseList = this.state.expenses.map((item) => {
12c05b0ab8d6a0ff42c54ec8615cd663695e66a6 OK

2020-11-09 09:27 UTC, SaharPerveen approved these changes, later dismissed
ok

2020-11-09 14:40 UTC, vesasuikkola approved these changes

2020-11-10 06:35 UTC, VilmaIkonen approved these changes

2020-11-10 06:36 UTC, merged