bugfix/category-list-to-ext-phrases: fixed integration with the new c…
BCH-REACT20S-Project-1-Group-2/BCH-REACT20S-Project-1-Group-2.github.io pull request #40
Opened 2020-11-10 08:18 UTC by vesasuikkola

…ategory list and ext. phrases/labels features

2020-11-10 14:07 UTC, VilmaIkonen requested changes
Few misspellings here to correct:

phrases/Categories.json:

Miscellenous --> Miscellaneous.
hair dresser --> hairdresser
(cable, cell, electricity, water, etc --> (cable, cell, electricity, water, etc.)

2020-11-11 12:07 UTC, vesasuikkola commented
> Miscellaneous

Fixed, also did the category name changes agreed for Spring 4

2020-11-11 12:11 UTC, VilmaIkonen approved these changes

2020-11-11 12:17 UTC, risman approved these changes

2020-11-11 12:19 UTC, merged