feature/exp-presentation: Expense data being populated from LS
BCH-REACT20S-Project-1-Group-2/BCH-REACT20S-Project-1-Group-2.github.io pull request #49
Opened 2020-11-12 18:31 UTC by khushboogoyal88

Expense data on Landing page will get populated by LS.

2020-11-12 20:08 UTC, risman approved these changes

2020-11-13 04:53 UTC, vesasuikkola requested changes

2020-11-13 04:53 UTC, vesasuikkola commented on frontend/src/components/BalancePresentation.js
> +      expenses: localStorage.getItem("total"),
We need also handling of empty LS, e.g.
```js
expenses: localStorage.getItem("total") || 0
```

2020-11-13 07:37 UTC, closed without merging

2020-11-13 07:37 UTC, khushboogoyal88 commented
Made different PR request