doc/style_guid: version 1.0
BCH-REACT20S-Project-1-Group-2/BCH-REACT20S-Project-1-Group-2.github.io pull request #7
Opened 2020-10-26 09:28 UTC by SaharPerveen

2020-10-27 08:18 UTC, vesasuikkola requested changes
Please add expected font sizes. Otherwise this looks all good to me!

2020-10-28 11:26 UTC, risman approved these changes

2020-10-28 12:36 UTC, VilmaIkonen approved these changes

2020-10-28 12:37 UTC, VilmaIkonen approved these changes

2020-10-28 13:28 UTC, vesasuikkola approved these changes

2020-10-28 13:29 UTC, merged